name: Index-3D-Prints

on:
  push:
    paths:
      - 'pnp/cad/**'
      - '.github/workflows/generate-3d-prints.yaml'
      - '!pnp/cad/3D-Prints/**'
    ignore-tags:
      - '*'
  pull_request:
    paths:
      - 'pnp/cad/**'
      - '!pnp/cad/3D-Prints/**'
    ignore-tags:
      - '*'

jobs:
  generate-obj:
    name: Generate STL files
    runs-on: ubuntu-latest

    steps:

    - name: Install FreeCAD Python library
      run:  |
        sudo add-apt-repository ppa:freecad-maintainers/freecad-stable
        sudo apt update
        sudo apt install python3
        sudo apt install freecad

    - name: Download repository
      uses: actions/checkout@v2

    - name: Generate 3D files
      run:  |
        cd pnp/cad
        rm -rf 3D-Prints
        mkdir 3D-Prints
        python3 export-3d-files.py

    - name: Commit files
      run:  |
        git add -f pnp/cad/3D-Prints
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git commit -m "CI: Generate 3D Prints" -a | exit 0

    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        branch: ${{ github.ref }}