name: Index-3D-Prints

on:
  push:
    paths:
      - 'pnp/cad/**'
      - 'pnp/cad/**.FCStd'
      - '.github/workflows/generate-3d-prints.yaml'
      - '!pnp/cad/3D-Prints/**'
    ignore-tags:
      - '*'
  pull_request:
    paths:
      - 'pnp/cad/**.FCStd'
      - '!pnp/cad/3D-Prints/**'
    ignore-tags:
      - '*'
  workflow_dispatch:
  release:
    types: [ published ]

jobs:
  generate-obj:
    name: Generate STL files
    runs-on: ubuntu-latest

    steps:

    - name: Install FreeCAD Python library
      run:  |
        sudo apt install python3

    - name: Download repository
      uses: actions/checkout@v2

    - name: Fetch FreeCAD
      uses: dsaltares/fetch-gh-release-asset@master
      with:
        repo: "FreeCAD/FreeCAD"
        version: "tags/0.19.2"
        file: "FreeCAD_0.19-24291-Linux-Conda_glibc2.12-x86_64.AppImage"
        target: "FreeCAD.AppImage"
        token: ${{ secrets.GITHUB_TOKEN }}

    - name: Generate 3D files
      run:  |
        sudo chown runner:docker FreeCAD.AppImage
        chmod +x FreeCAD.AppImage
        ./FreeCAD.AppImage --appimage-extract > /dev/null
        cd pnp/cad
        rm -rf 3D-Prints
        mkdir 3D-Prints
        python3 export-3d-files.py
        cd 3D-Prints
        zip -r -j ../3d-prints.zip *

    - name: upload 3D print results
      uses: actions/upload-artifact@v2
      with:
        name: 3d-prints
        path: pnp/cad/3D-Prints       

    - name: Upload Artifacts to Release
      uses: softprops/action-gh-release@v1
      if: github.event_name == 'release'
      with:
        files: |
          pnp/cad/3d-prints.zip

