name: generate-feeder-pcb-artifacts

on:
  push:
    paths:
      - 'feeder/pcb/**.kicad_sch'
      - 'feeder/pcb/**.kicad_pcb'
      - 'feeder/pcb/**.kibot.yaml'
      - '.github/workflows/generate-feeder-pcb-artifacts.yaml'
      - '**.kibot.yaml'
    ignore-tags:
      - '*'
  pull_request:
    paths:
      - 'feeder/pcb/**.sch'
      - 'feeder/pcb/**.kicad_pcb'
      - 'feeder/pcb/**.kibot.yaml'
      - '.github/workflows/generate-feeder-pcb-artifacts.yaml'
      - '**.kibot.yaml'
    ignore-tags:
      - '*'
  release:
    types: [ published ]      

env:
  repo: index-machines/index
  main_branch: master

jobs:
  generate-artifacts:
    runs-on: ubuntu-latest
    container: setsoft/kicad_auto:dev_k6
      
    steps:
    - name: Update system repositories
      run:  |
        apt update
        apt -y install git git-lfs zip librsvg2-bin imagemagick
        
    - name: Print Repo Info
      run: | 
        echo 'repo: ${{github.repository}}'

    - name: Checkout Repository
      uses: actions/checkout@v3
      with:
        lfs: true

    - name: Extract branch name
      shell: bash
      run: echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"
      id: extract_branch            

    - name: Update the PCBs with the git hash
      if: github.event_name == 'release' || steps.extract_branch.outputs.branch == env.main_branch    
      run: |
        export COMMIT=$(git rev-parse --short HEAD)
        echo "COMMIT = ${COMMIT}"
        sed -i "s!<<hash>>!${COMMIT}!" feeder/pcb/mobo/mobo.kicad_pcb
        sed -i "s!<<hash>>!${COMMIT}!" feeder/pcb/feederFloor/feederFloor.kicad_pcb
        sed -i "s!<<hash>>!${COMMIT}!" feeder/pcb/indexingWheel/indexingWheel.kicad_pcb

    - name: Update the PCBs with the git hash and Beta
      if: steps.extract_branch.outputs.branch != env.main_branch    
      run: |
        export COMMIT=$(git rev-parse --short HEAD)
        echo "COMMIT = ${COMMIT}"
        sed -i "s!<<hash>>!BETA-${COMMIT}!" feeder/pcb/mobo/mobo.kicad_pcb
        sed -i "s!<<hash>>!BETA-${COMMIT}!" feeder/pcb/feederFloor/feederFloor.kicad_pcb
        sed -i "s!<<hash>>!BETA-${COMMIT}!" feeder/pcb/indexingWheel/indexingWheel.kicad_pcb        

    - name: Run feeder mobo KiBot
      run: cd feeder/pcb/mobo && kibot -c config.kibot.yaml -e mobo.kicad_sch -b mobo.kicad_pcb -d export

    - name: Compress feeder mobo Gerbers for PCB Fab
      run: cd feeder/pcb/mobo/export/gerbers && zip -r -j ../feeder_mobo_gerbers.zip * 
      
    - name: Prepare Output Artifact
      if: github.event_name == 'release'    
      run: |
        cd feeder/pcb/mobo/export/
        zip -r -j ../feeder_mobo_files.zip *      

    - name: upload mobo artifacts
      uses: actions/upload-artifact@v2
      with:
        name: feeder_mobo_output
        path: feeder/pcb/mobo/export        

    - name: Run indexingWheel KiBot
      run: cd feeder/pcb/indexingWheel && kibot -c ../../../config-blank.kibot.yaml -e indexingWheel.kicad_sch -b indexingWheel.kicad_pcb -d export

    - name: Compress indexingWheel Gerbers for PCB Fab
      run: cd feeder/pcb/indexingWheel/export/gerbers && zip -r -j ../feeder_indexingWheel_gerbers.zip *
      
    - name: Prepare Output Artifact
      if: github.event_name == 'release'    
      run: |
        cd feeder/pcb/indexingWheel/export/
        zip -r -j ../feeder_indexingWheel_files.zip *            

    - name: upload indexingWheel results
      uses: actions/upload-artifact@v2
      with:
        name: feeder_indexingWheel_output
        path: feeder/pcb/indexingWheel/export

    - name: Run feederFloor KiBot
      run: cd feeder/pcb/feederFloor && kibot -c ../../../config.kibot.yaml -e feederFloor.kicad_sch -b feederFloor.kicad_pcb -d export

    - name: Compress feederFloor Gerbers for PCB Fab
      run: cd feeder/pcb/feederFloor/export/gerbers && zip -r -j ../feeder_feederFloor_gerbers.zip *
      
    - name: Prepare Output Artifact
      if: github.event_name == 'release'    
      run: |
        cd feeder/pcb/feederFloor/export/
        zip -r -j ../feeder_feederFloor_files.zip *      

    - name: upload feederFloor results
      uses: actions/upload-artifact@v2
      with:
        name: feeder_feederFloor_output
        path: feeder/pcb/feederFloor/export

    - name: Upload Artifacts to Release
      uses: softprops/action-gh-release@v1
      if: github.event_name == 'release'
      with:
        files: |
          feeder/pcb/feederFloor/feeder_feederFloor_files.zip
          feeder/pcb/indexingWheel/feeder_indexingWheel_files.zip
          feeder/pcb/mobo/feeder_mobo_files.zip
     
