name: generate-3d-print-information

on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
  
jobs:
  generate-obj:
    name: Generate G-Code files and info for documentation
    runs-on: ubuntu-20.04

    steps:
    - name: Update system repositories
      run:  sudo apt update

    - name: Install libcanberra-gtk-module libcanberra-gtk3-module
      run:  sudo apt install libcanberra-gtk-module libcanberra-gtk3-module

    - name: Download PrusaSlicer
      run: wget --content-disposition --quiet https://github.com/prusa3d/PrusaSlicer/releases/download/version_2.3.1/PrusaSlicer-2.3.1+linux-x64-202104161339.AppImage

    - name: Install PrusaSlicer 1
      run: mv PrusaSlicer-* PrusaSlicer.AppImage

    - name: Install PrusaSlicer 2
      run: export SSL_CERT_FILE=/etc/ssl/certs/ca-certificates.crt

    - name: Install PrusaSlicer 3
      run: chmod a+x PrusaSlicer.AppImage 

    - name: Download repository
      uses: actions/checkout@v2

    - name: Generate 3D files
      run: |
        cd pnp/cad
        python slice-3d-files.py

    - name: Commit files
      run: |
        git add -f doc/content/en/docs/reference/fdm
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git commit -m "CI: Generate 3D print information" -a | exit 0

    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        branch: ${{ github.ref }}
