name: kicad-exports

on:
  push:
    branches: [master]
    paths:
    - '**.sch'
    - '**.kicad_pcb'
  pull_request:
    branches: [master]
    paths:
    - '**.sch'
    - '**.kicad_pcb'
      
jobs:
    pnp_mobo:
      runs-on: ubuntu-latest
      steps:
      - uses: actions/checkout@v2
      - uses: nerdyscout/kicad-exports@v2.2
        with:
          config: pnp/pcb/mobo/config.kiplot.yaml
          board: pnp/pcb/mobo/mobo.kicad_pcb
          schema: pnp/pcb/mobo/mobo.sch
          dir: pnp/pcb/mobo
      - name: upload results
        uses: actions/upload-artifact@v2
        with:
          name: ${{ github.job }}
          path: pnp/pcb/mobo/gerbers
          
    pnp_piggyback:
      runs-on: ubuntu-latest
      needs: pnp_mobo
      steps:
      - uses: actions/checkout@v2
      - uses: nerdyscout/kicad-exports@v2.2
        with:
          config: pnp/pcb/piggyback/config.kiplot.yaml
          board: pnp/pcb/piggyback/piggyback.kicad_pcb
          schema: pnp/pcb/piggyback/piggyback.sch
          dir: pnp/pcb/piggyback
      - name: upload results
        uses: actions/upload-artifact@v2
        with:
          name: ${{ github.job }}
          path: pnp/pcb/piggyback/gerbers
          
    feeder_mobo:
      runs-on: ubuntu-latest
      needs: pnp_piggyback
      steps:
      - uses: actions/checkout@v2
      - uses: nerdyscout/kicad-exports@v2.2
        with:
          config: feeder/pcb/mobo/config.kiplot.yaml
          board: feeder/pcb/mobo/mobo.kicad_pcb
          schema: feeder/pcb/mobo/mobo.sch
          dir: feeder/pcb/mobo
      - name: upload results
        uses: actions/upload-artifact@v2
        with:
          name: ${{ github.job }}
          path: feeder/pcb/mobo/gerbers

    commit:
      runs-on: ubuntu-latest
      needs: [ pnp_mobo, pnp_piggyback, feeder_mobo ]
      steps:
      - uses: actions/checkout@v2
      - uses: actions/download-artifact@v2
        with:
          name: pnp_mobo
          path: pnp/pcb/mobo/gerbers/
      - uses: actions/download-artifact@v2
        with:
          name: pnp_piggyback
          path: pnp/pcb/piggyback/gerbers/
      - uses: actions/download-artifact@v2
        with:
          name: feeder_mobo
          path: feeder/pcb/mobo/gerbers/
      - uses: github-actions-x/commit@v2.7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          rebase: 'true'
          files: output/*
          name: kicad-export
          email: ci@github 
          commit-message: auto update

